Orc support
GoogleCloudPlatform/dlp-dataflow-deidentification pull request #172
Opened 2023-10-16 10:58 UTC by chitara-01

<h4> Summary (Short summary of what is being done) : </h4>
Update README with instructions to run DLP Dataflow templates for ORC files
<br>
<h4> Description (Describe in detail the fix made) : </h4>
Adding instructions to use DLP Dataflow templates (inspection and de-identification) for input ORC files with limitations.
<br>
<h4> Bug ID (if any) : </h4>
<br>
<h4> Public Documentation (if any) : </h4>
<br>
<h4> TESTED (Test Cases with scenario and description - must have 1 positive and 1 negative scenario) : </h4>

2023-10-17 04:18 UTC, saurabhgadia4 approved these changes

2023-10-17 20:38 UTC, catherinerosesantos requested changes

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +1. output BigQuery dataset as tables, or
1. output BigQuery dataset as tables, or --> To write the de-identified files to a BigQuery table:
OR
To write the de-identified files to BigQuery tables

(depending on which one is more accurate)

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +2. output GCS storage bucket as de-identified ORC files.
output GCS storage bucket as de-identified ORC files. --> To write the de-identified files to an output bucket:

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +In the above command, replace <i>output_storage_bucket</i> with the GCS storage bucket URI where you want to store the
GCS storage bucket URI --> URI of the Cloud Storage bucket

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +Input files with varying schema is supported by the de-identification pipeline. Currently, it can process only Primitive
The de-identification pipeline supports input files with varying schemas.

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +Input files with varying schema is supported by the de-identification pipeline. Currently, it can process only Primitive
Primitive --> primitive

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +data types available in ORC format when the results are stored in output GCS storage bucket.
in output GCS storage bucket. --> in an output Cloud Storage bucket.

2023-10-17 20:38 UTC, catherinerosesantos commented on README.md
> +For sample data in ORC file format, refer [mock-data](.github/mock-data).
refer --> refer to

There's another instance of this in the Parquet section. Please edit that too.

2023-10-18 05:44 UTC, catherinerosesantos commented on README.md
> +2. To write the de-identified files to Cloud storage bucket:
to Cloud storage --> to a Cloud Storage

2023-10-18 05:45 UTC, catherinerosesantos approved these changes

2023-10-18 09:40 UTC, dup05 approved these changes

2023-10-18 09:47 UTC, merged